import { discover } from "./discovery";
import { AccountsError } from "./errors";
import type { AccountsConfig } from "./types";

export class TokenRefreshError extends AccountsError {
    constructor(message: string) {
        super("token_refresh_failed", message);
        this.name = "TokenRefreshError";
    }
}

export class TokenRevocationError extends AccountsError {
    constructor(message: string) {
        super("token_revocation_failed", message);
        this.name = "TokenRevocationError";
    }
}

export interface TokenResponse {
    access_token: string;
    /**
     * A new refresh token, if rotation is enabled (it always should be —
     * this SDK does not support non-rotating refresh tokens). Callers MUST
     * discard the old refresh token and persist this one; the old token
     * is invalidated server-side as part of this exchange.
     */
    refresh_token?: string;
    id_token?: string;
    token_type: string;
    expires_in: number;
    scope?: string;
}

/**
 * Exchanges an authorization code for tokens. Requires the codeVerifier
 * generated by buildAuthorizationUrl() — PKCE is not optional.
 */
export async function exchangeCodeForTokens(
    config: AccountsConfig,
    params: { code: string; codeVerifier: string; clientSecret?: string },
): Promise<TokenResponse> {
    if (!config.redirectUri) {
        throw new AccountsError(
            "invalid_config",
            "AccountsConfig.redirectUri is required for token exchange",
        );
    }

    const discovery = await discover(config);
    const body = new URLSearchParams({
        grant_type: "authorization_code",
        code: params.code,
        redirect_uri: config.redirectUri,
        client_id: config.clientId,
        code_verifier: params.codeVerifier,
    });
    if (params.clientSecret) {
        body.set("client_secret", params.clientSecret);
    }

    return requestToken(
        discovery.token_endpoint,
        body,
        "Authorization code exchange failed",
    );
}

/**
 * Exchanges a refresh token for a new access/refresh token pair. The server
 * rotates the refresh token atomically — the token passed in is invalidated
 * as part of this call and MUST NOT be reused, even if this call fails
 * partway through (the response, not the request, is the source of truth
 * for whether rotation happened; a network error after the server processed
 * the request still invalidates the old token).
 */
export async function refreshTokens(
    config: AccountsConfig,
    refreshToken: string,
    options: { clientSecret?: string } = {},
): Promise<TokenResponse> {
    const discovery = await discover(config);
    const body = new URLSearchParams({
        grant_type: "refresh_token",
        refresh_token: refreshToken,
        client_id: config.clientId,
    });
    if (options.clientSecret) {
        body.set("client_secret", options.clientSecret);
    }

    return requestToken(discovery.token_endpoint, body, "Token refresh failed");
}

async function requestToken(
    tokenEndpoint: string,
    body: URLSearchParams,
    errorPrefix: string,
): Promise<TokenResponse> {
    let response: Response;
    try {
        response = await fetch(tokenEndpoint, {
            method: "POST",
            headers: { "content-type": "application/x-www-form-urlencoded" },
            body,
        });
    } catch {
        throw new TokenRefreshError(
            `${errorPrefix}: could not reach token endpoint`,
        );
    }

    let payload: unknown;
    try {
        payload = await response.json();
    } catch {
        throw new TokenRefreshError(
            `${errorPrefix}: token endpoint returned non-JSON response`,
        );
    }

    if (!response.ok) {
        // OAuth error responses carry `error` and optionally `error_description`
        // (RFC 6749 §5.2) — safe to surface, never contains the token itself.
        const record = payload as Record<string, unknown>;
        const code =
            typeof record.error === "string" ? record.error : "unknown_error";
        const description =
            typeof record.error_description === "string"
                ? record.error_description
                : undefined;
        throw new TokenRefreshError(
            `${errorPrefix}: ${code}${description ? ` (${description})` : ""}`,
        );
    }

    return payload as TokenResponse;
}

/**
 * Revokes a token (access or refresh) per RFC 7009. Best-effort from the
 * caller's perspective — if the provider is unreachable, the caller should
 * still treat the local session as ended and clear stored tokens; revocation
 * failing does not mean the token is still valid for use.
 */
export async function revokeToken(
    config: AccountsConfig,
    token: string,
    tokenTypeHint?: "access_token" | "refresh_token",
): Promise<void> {
    const discovery = await discover(config);
    if (!discovery.revocation_endpoint) {
        throw new TokenRevocationError(
            "Provider does not advertise a revocation_endpoint",
        );
    }

    const body = new URLSearchParams({
        token,
        client_id: config.clientId,
    });
    if (tokenTypeHint) {
        body.set("token_type_hint", tokenTypeHint);
    }

    let response: Response;
    try {
        response = await fetch(discovery.revocation_endpoint, {
            method: "POST",
            headers: { "content-type": "application/x-www-form-urlencoded" },
            body,
        });
    } catch {
        throw new TokenRevocationError("Could not reach revocation endpoint");
    }

    // RFC 7009 §2.2: servers respond 200 even for already-invalid tokens,
    // to avoid leaking whether a token was ever valid. Only non-200 is a
    // genuine failure worth surfacing.
    if (!response.ok) {
        throw new TokenRevocationError(
            `Revocation endpoint returned ${response.status}`,
        );
    }
}
